import { US_STATES, YES_NO } from "./common";
import type { FormSchema } from "./types";

// Official NYS DMV form: Report of Motor Vehicle Accident (MV-104).
// Required within 10 days when accident involves injury, death, or
// property damage exceeding $1,000 (VTL §605).

export const piMv104Form: FormSchema = {
  id: "pi-mv104-form",
  title: "MV-104",
  longTitle: "Report of Motor Vehicle Accident (MV-104) — NYS DMV",
  appliesTo: ["personalInjury"],
  sections: [
    {
      id: "accident",
      title: "1. Accident information",
      items: [
        { id: "accidentDate", type: "date", label: "Date of accident", required: true },
        { id: "accidentTime", type: "text", label: "Time (24-hour)", placeholder: "15:30" },
        { id: "accidentDay", type: "select", label: "Day of week", options: [
          { value: "sun", label: "Sunday" },
          { value: "mon", label: "Monday" },
          { value: "tue", label: "Tuesday" },
          { value: "wed", label: "Wednesday" },
          { value: "thu", label: "Thursday" },
          { value: "fri", label: "Friday" },
          { value: "sat", label: "Saturday" },
        ] },
        { id: "county", type: "text", label: "County" },
        { id: "city", type: "text", label: "City / town / village" },
        { id: "roadOnWhichAccidentOccurred", type: "text", label: "Road on which accident occurred" },
        { id: "atIntersectionWith", type: "text", label: "At intersecting street or nearest landmark" },
        { id: "policeNotified", type: "radio", label: "Police notified?", options: YES_NO },
        { id: "policeAgency", type: "text", label: "Police agency", visibleIf: { fieldId: "policeNotified", equals: "yes" } },
        { id: "policeReportNumber", type: "text", label: "Police report number" },
      ],
    },
    {
      id: "vehicle1",
      title: "2. Vehicle 1 — driver / owner",
      items: [
        { id: "v1DriverName", type: "text", label: "Driver name", required: true },
        { id: "v1DriverLicense", type: "text", label: "Driver license number" },
        { id: "v1DriverLicenseState", type: "select", label: "License state", options: US_STATES },
        { id: "v1DriverDob", type: "date", label: "Driver date of birth" },
        { id: "v1DriverStreet", type: "text", label: "Driver address" },
        { id: "v1DriverCity", type: "text", label: "City" },
        { id: "v1DriverState", type: "select", label: "State", options: US_STATES },
        { id: "v1DriverZip", type: "text", label: "ZIP code" },
        { id: "v1DriverPhone", type: "text", label: "Telephone" },
        { id: "v1OwnerName", type: "text", label: "Vehicle owner (if different from driver)" },
        { id: "v1OwnerAddress", type: "text", label: "Owner address" },
        { id: "v1Plate", type: "text", label: "License plate number" },
        { id: "v1PlateState", type: "select", label: "Plate state", options: US_STATES },
        { id: "v1Vin", type: "text", label: "VIN" },
        { id: "v1Year", type: "text", label: "Year" },
        { id: "v1Make", type: "text", label: "Make" },
        { id: "v1Model", type: "text", label: "Model" },
        { id: "v1InsuranceCarrier", type: "text", label: "Insurance carrier" },
        { id: "v1PolicyNumber", type: "text", label: "Policy number" },
        { id: "v1DamageDescription", type: "textarea", label: "Damage to vehicle 1" },
        { id: "v1EstimatedDamage", type: "currency", label: "Estimated property damage" },
      ],
    },
    {
      id: "vehicle2",
      title: "3. Vehicle 2 — driver / owner",
      items: [
        { id: "v2DriverName", type: "text", label: "Driver name" },
        { id: "v2DriverLicense", type: "text", label: "Driver license number" },
        { id: "v2DriverLicenseState", type: "select", label: "License state", options: US_STATES },
        { id: "v2DriverDob", type: "date", label: "Driver date of birth" },
        { id: "v2DriverStreet", type: "text", label: "Driver address" },
        { id: "v2DriverCity", type: "text", label: "City" },
        { id: "v2DriverState", type: "select", label: "State", options: US_STATES },
        { id: "v2DriverZip", type: "text", label: "ZIP code" },
        { id: "v2DriverPhone", type: "text", label: "Telephone" },
        { id: "v2OwnerName", type: "text", label: "Vehicle owner (if different)" },
        { id: "v2OwnerAddress", type: "text", label: "Owner address" },
        { id: "v2Plate", type: "text", label: "License plate number" },
        { id: "v2PlateState", type: "select", label: "Plate state", options: US_STATES },
        { id: "v2Vin", type: "text", label: "VIN" },
        { id: "v2Year", type: "text", label: "Year" },
        { id: "v2Make", type: "text", label: "Make" },
        { id: "v2Model", type: "text", label: "Model" },
        { id: "v2InsuranceCarrier", type: "text", label: "Insurance carrier" },
        { id: "v2PolicyNumber", type: "text", label: "Policy number" },
        { id: "v2DamageDescription", type: "textarea", label: "Damage to vehicle 2" },
        { id: "v2EstimatedDamage", type: "currency", label: "Estimated property damage" },
      ],
    },
    {
      id: "injured",
      title: "4. Injured / killed persons",
      items: [
        {
          kind: "repeating-group",
          id: "injuredPersons",
          label: "Injured persons",
          itemLabel: "Person",
          fields: [
            { id: "name", type: "text", label: "Name", required: true },
            { id: "address", type: "text", label: "Address" },
            { id: "dob", type: "date", label: "Date of birth" },
            { id: "role", type: "select", label: "Position", options: [
              { value: "driver", label: "Driver" },
              { value: "passenger", label: "Passenger" },
              { value: "pedestrian", label: "Pedestrian" },
              { value: "bicyclist", label: "Bicyclist" },
              { value: "motorcyclist", label: "Motorcyclist" },
            ] },
            { id: "injurySeverity", type: "select", label: "Severity", options: [
              { value: "K", label: "K — Killed" },
              { value: "A", label: "A — Incapacitating injury" },
              { value: "B", label: "B — Non-incapacitating injury" },
              { value: "C", label: "C — Possible injury" },
              { value: "O", label: "O — No injury" },
            ] },
            { id: "transportedTo", type: "text", label: "Transported to (hospital)" },
          ],
        },
      ],
    },
    {
      id: "description",
      title: "5. Description of accident",
      items: [
        { id: "weather", type: "select", label: "Weather", options: [
          { value: "clear", label: "Clear" },
          { value: "cloudy", label: "Cloudy" },
          { value: "rain", label: "Rain" },
          { value: "snow", label: "Snow" },
          { value: "fog", label: "Fog" },
          { value: "other", label: "Other" },
        ] },
        { id: "roadSurface", type: "select", label: "Road surface", options: [
          { value: "dry", label: "Dry" },
          { value: "wet", label: "Wet" },
          { value: "snowIce", label: "Snow / Ice" },
          { value: "muddy", label: "Muddy" },
        ] },
        { id: "lighting", type: "select", label: "Light condition", options: [
          { value: "day", label: "Daylight" },
          { value: "dawn-dusk", label: "Dawn / Dusk" },
          { value: "darkLit", label: "Dark — road lighted" },
          { value: "darkUnlit", label: "Dark — road not lighted" },
        ] },
        { id: "trafficControl", type: "select", label: "Traffic control", options: [
          { value: "none", label: "None" },
          { value: "signal", label: "Traffic signal" },
          { value: "stop-sign", label: "Stop sign" },
          { value: "yield", label: "Yield sign" },
          { value: "officer", label: "Police officer" },
          { value: "other", label: "Other" },
        ] },
        { id: "narrative", type: "textarea", label: "Describe accident in your own words", required: true },
      ],
    },
    {
      id: "certification",
      title: "6. Certification",
      description:
        "I certify that the information contained in this report is true to the best of my knowledge. Filing a false report is a misdemeanor (VTL §605(b)).",
      items: [
        { id: "filerName", type: "text", label: "Filed by (typed name)" },
        { id: "filerRole", type: "select", label: "Filer role", options: [
          { value: "driver", label: "Driver" },
          { value: "owner", label: "Owner" },
          { value: "passenger", label: "Passenger" },
          { value: "attorney", label: "Attorney" },
        ] },
        { id: "signatureDate", type: "date", label: "Date signed" },
      ],
    },
  ],
};
