import { YES_NO } from "./common";
import type { FormSchema } from "./types";

export const reDueDiligence: FormSchema = {
  id: "re-due-diligence",
  title: "Due Diligence",
  longTitle: "Real Estate — Title Searches, Violations & Due Diligence",
  appliesTo: ["realEstate"],
  sections: [
    {
      id: "titleSearch",
      title: "Title search",
      description:
        "The title search examines the chain of title going back at least 40 years (NY RPL §612). Results are reviewed for gaps in chain of title, outstanding mortgages, judgments, liens, and encumbrances.",
      items: [
        {
          id: "titleSearchOrdered",
          type: "radio",
          label: "Title search ordered?",
          options: YES_NO,
        },
        {
          id: "titleSearchCompany",
          type: "text",
          label: "Title search company",
          visibleIf: { fieldId: "titleSearchOrdered", equals: "yes" },
        },
        {
          id: "titleSearchOrderDate",
          type: "date",
          label: "Search ordered date",
          visibleIf: { fieldId: "titleSearchOrdered", equals: "yes" },
        },
        {
          id: "titleSearchReceivedDate",
          type: "date",
          label: "Search results received date",
          visibleIf: { fieldId: "titleSearchOrdered", equals: "yes" },
        },
        {
          id: "titleExceptions",
          type: "textarea",
          label: "Title exceptions / Schedule B exceptions",
          help: "List easements, restrictions, and other exceptions shown on the title commitment",
          visibleIf: { fieldId: "titleSearchOrdered", equals: "yes" },
        },
        {
          id: "titleDefectsFound",
          type: "radio",
          label: "Title defects or objections found?",
          options: YES_NO,
          visibleIf: { fieldId: "titleSearchOrdered", equals: "yes" },
        },
        {
          id: "titleDefectDetails",
          type: "textarea",
          label: "Title defect / objection details",
          visibleIf: { fieldId: "titleDefectsFound", equals: "yes" },
        },
        {
          id: "titleDefectsCleared",
          type: "radio",
          label: "All title objections cleared?",
          options: YES_NO,
          visibleIf: { fieldId: "titleDefectsFound", equals: "yes" },
        },
      ],
    },
    {
      id: "judgmentLienSearch",
      title: "Judgment & lien search",
      description:
        "Searches are run against the seller in all counties where seller has lived or done business, plus the property county. Includes judgment liens, federal tax liens, mechanics' liens, and UCC filings.",
      items: [
        {
          id: "judgmentSearchCompleted",
          type: "radio",
          label: "Judgment / lien search completed?",
          options: YES_NO,
        },
        {
          id: "judgmentsFound",
          type: "radio",
          label: "Judgments found against seller?",
          options: YES_NO,
          visibleIf: { fieldId: "judgmentSearchCompleted", equals: "yes" },
        },
        {
          id: "judgmentDetails",
          type: "textarea",
          label: "Judgment details (creditor, amount, court)",
          visibleIf: { fieldId: "judgmentsFound", equals: "yes" },
        },
        {
          id: "judgmentsResolved",
          type: "radio",
          label: "Judgments to be satisfied at closing?",
          options: YES_NO,
          visibleIf: { fieldId: "judgmentsFound", equals: "yes" },
        },
        {
          id: "federalTaxLienFound",
          type: "radio",
          label: "Federal tax lien found?",
          options: YES_NO,
          visibleIf: { fieldId: "judgmentSearchCompleted", equals: "yes" },
        },
        {
          id: "federalTaxLienDetails",
          type: "textarea",
          label: "Federal tax lien details",
          visibleIf: { fieldId: "federalTaxLienFound", equals: "yes" },
        },
        {
          id: "mechanicsLienFound",
          type: "radio",
          label: "Mechanics' lien found (NY Lien Law Art. 2)?",
          options: YES_NO,
          visibleIf: { fieldId: "judgmentSearchCompleted", equals: "yes" },
        },
        {
          id: "mechanicsLienDetails",
          type: "textarea",
          label: "Mechanics' lien details",
          visibleIf: { fieldId: "mechanicsLienFound", equals: "yes" },
        },
        {
          id: "estateSearchRequired",
          type: "radio",
          label: "Estate / probate search required (seller inherited property)?",
          options: YES_NO,
        },
        {
          id: "estateSearchNotes",
          type: "textarea",
          label: "Estate search notes",
          visibleIf: { fieldId: "estateSearchRequired", equals: "yes" },
        },
      ],
    },
    {
      id: "nycViolations",
      title: "NYC open violations search",
      description:
        "NYC properties are subject to open violations from multiple agencies. DOB and ECB violations run with the property and must be resolved before closing or escrow held. HPD violations are required for multi-unit residential buildings.",
      items: [
        {
          id: "nycViolationsApplicable",
          type: "radio",
          label: "Is this a NYC property (violations search required)?",
          options: YES_NO,
        },
        {
          id: "dobSearchCompleted",
          type: "radio",
          label: "DOB (Dept. of Buildings) violations search completed?",
          options: YES_NO,
          visibleIf: { fieldId: "nycViolationsApplicable", equals: "yes" },
        },
        {
          id: "dobOpenViolations",
          type: "radio",
          label: "Open DOB violations found?",
          options: YES_NO,
          visibleIf: { fieldId: "dobSearchCompleted", equals: "yes" },
        },
        {
          id: "dobViolationDetails",
          type: "textarea",
          label: "DOB violation details",
          visibleIf: { fieldId: "dobOpenViolations", equals: "yes" },
        },
        {
          id: "dobViolationsResolved",
          type: "radio",
          label: "DOB violations to be resolved / escrowed at closing?",
          options: YES_NO,
          visibleIf: { fieldId: "dobOpenViolations", equals: "yes" },
        },
        {
          id: "ecbSearchCompleted",
          type: "radio",
          label: "ECB (Environmental Control Board / OATH) violations search completed?",
          options: YES_NO,
          visibleIf: { fieldId: "nycViolationsApplicable", equals: "yes" },
        },
        {
          id: "ecbOpenViolations",
          type: "radio",
          label: "Open ECB violations found?",
          options: YES_NO,
          visibleIf: { fieldId: "ecbSearchCompleted", equals: "yes" },
        },
        {
          id: "ecbViolationDetails",
          type: "textarea",
          label: "ECB violation details",
          visibleIf: { fieldId: "ecbOpenViolations", equals: "yes" },
        },
        {
          id: "hpdSearchCompleted",
          type: "radio",
          label: "HPD (Housing Preservation & Development) violations search completed?",
          help: "Required for multi-unit residential buildings (3+ units)",
          options: YES_NO,
          visibleIf: { fieldId: "nycViolationsApplicable", equals: "yes" },
        },
        {
          id: "hpdOpenViolations",
          type: "radio",
          label: "Open HPD violations found?",
          options: YES_NO,
          visibleIf: { fieldId: "hpdSearchCompleted", equals: "yes" },
        },
        {
          id: "hpdViolationDetails",
          type: "textarea",
          label: "HPD violation details",
          visibleIf: { fieldId: "hpdOpenViolations", equals: "yes" },
        },
      ],
    },
    {
      id: "coAndZoning",
      title: "Certificate of Occupancy & zoning",
      description:
        "NY requires a Certificate of Occupancy (CO) for buildings completed after 1938. The CO must reflect current legal use. Lenders typically require a clean CO; title companies may except any CO issues from coverage.",
      items: [
        {
          id: "coStatus",
          type: "select",
          label: "Certificate of Occupancy status",
          options: [
            { value: "final-co", label: "Final CO — exists and matches current use" },
            { value: "tco", label: "Temporary CO (TCO) — in effect" },
            { value: "no-co", label: "No CO on file (pre-1938 or missing)" },
            { value: "co-mismatch", label: "CO exists but does not match current use / improvements" },
            { value: "not-required", label: "Not required (vacant land)" },
          ],
        },
        {
          id: "coNumber",
          type: "text",
          label: "CO number / BIS job number",
          visibleIf: { fieldId: "coStatus", equals: "final-co" },
        },
        {
          id: "tcoExpirationDate",
          type: "date",
          label: "TCO expiration date",
          visibleIf: { fieldId: "coStatus", equals: "tco" },
        },
        {
          id: "coIssueNotes",
          type: "textarea",
          label: "CO issue / mismatch notes",
          visibleIf: { fieldId: "coStatus", equals: "co-mismatch" },
        },
        {
          id: "zoningCompliant",
          type: "radio",
          label: "Current use is zoning-compliant?",
          options: YES_NO,
        },
        {
          id: "zoningNotes",
          type: "textarea",
          label: "Zoning notes (variance, non-conforming use, etc.)",
          visibleIf: { fieldId: "zoningCompliant", equals: "no" },
        },
        {
          id: "landmarkStatus",
          type: "radio",
          label: "Property is a NYC landmark or in a historic district?",
          help: "LPC (Landmarks Preservation Commission) approval required for exterior alterations",
          options: YES_NO,
        },
        {
          id: "landmarkDetails",
          type: "text",
          label: "Landmark designation / historic district name",
          visibleIf: { fieldId: "landmarkStatus", equals: "yes" },
        },
      ],
    },
    {
      id: "coopUcc",
      title: "Co-op UCC search",
      description:
        "For co-op purchases, a UCC search against the seller is run to identify any security interest in the shares. The buyer's lender will file a UCC-1 to perfect its interest in the shares and proprietary lease.",
      items: [
        {
          id: "uccSearchApplicable",
          type: "radio",
          label: "UCC search applicable (co-op purchase)?",
          options: YES_NO,
        },
        {
          id: "uccSearchCompleted",
          type: "radio",
          label: "UCC search completed against seller?",
          options: YES_NO,
          visibleIf: { fieldId: "uccSearchApplicable", equals: "yes" },
        },
        {
          id: "uccLiensFound",
          type: "radio",
          label: "Existing UCC liens found on shares?",
          options: YES_NO,
          visibleIf: { fieldId: "uccSearchCompleted", equals: "yes" },
        },
        {
          id: "uccLienDetails",
          type: "textarea",
          label: "UCC lien details (secured party, filing number)",
          visibleIf: { fieldId: "uccLiensFound", equals: "yes" },
        },
        {
          id: "uccLiensToBeTerminated",
          type: "radio",
          label: "Existing UCC liens to be terminated / released at closing?",
          options: YES_NO,
          visibleIf: { fieldId: "uccLiensFound", equals: "yes" },
        },
      ],
    },
  ],
};
