import { addressFields, DEBTOR_LIABLE } from "./common";
import type { FormSchema } from "./types";

export const schedule106AB: FormSchema = {
  id: "106AB",
  title: "Schedule A/B — Property",
  longTitle: "Schedule A/B — Property You Own or Have an Interest In",
  appliesTo: ["chapter7", "chapter13"],
  sections: [
    {
      id: "part1Residence",
      title: "Part 1 — Residence, Building, Land, or Other Real Estate",
      description: "List every parcel of real estate the debtor owns or has an interest in.",
      items: [
        {
          kind: "repeating-group",
          id: "realEstate",
          label: "Real estate",
          itemLabel: "Property",
          fields: [
            { id: "description", type: "text", label: "Description (e.g., single-family home)" },
            ...addressFields("location"),
            {
              id: "ownershipType",
              type: "select",
              label: "Type of ownership",
              options: [
                { value: "feeSimple", label: "Fee simple" },
                { value: "tenantsByEntireties", label: "Tenants by the entireties" },
                { value: "jointTenants", label: "Joint tenants" },
                { value: "tenantsInCommon", label: "Tenants in common" },
                { value: "lifeEstate", label: "Life estate" },
                { value: "other", label: "Other" },
              ],
            },
            {
              id: "interestHolder",
              type: "select",
              label: "Who has an interest in the property",
              options: DEBTOR_LIABLE,
            },
            { id: "currentValue", type: "currency", label: "Current value of entire property" },
            { id: "debtorValue", type: "currency", label: "Current value of debtor's portion" },
            { id: "lienAmount", type: "currency", label: "Amount of secured claim against the property" },
            { id: "communityProperty", type: "checkbox", label: "Community property" },
          ],
        },
      ],
    },
    {
      id: "part2Vehicles",
      title: "Part 2 — Vehicles",
      items: [
        {
          kind: "repeating-group",
          id: "vehicles",
          label: "Vehicles, watercraft, aircraft",
          itemLabel: "Vehicle",
          fields: [
            {
              id: "vehicleType",
              type: "select",
              label: "Type",
              options: [
                { value: "car", label: "Car" },
                { value: "truck", label: "Truck" },
                { value: "motorcycle", label: "Motorcycle" },
                { value: "rv", label: "Recreational vehicle / camper" },
                { value: "boat", label: "Boat / watercraft" },
                { value: "aircraft", label: "Aircraft" },
                { value: "other", label: "Other" },
              ],
            },
            { id: "make", type: "text", label: "Make" },
            { id: "model", type: "text", label: "Model" },
            { id: "year", type: "number", label: "Year" },
            { id: "mileage", type: "number", label: "Mileage" },
            { id: "otherInfo", type: "text", label: "Other info (color, condition, VIN)" },
            { id: "currentValue", type: "currency", label: "Current value" },
            { id: "debtorValue", type: "currency", label: "Current value of debtor's portion" },
            {
              id: "interestHolder",
              type: "select",
              label: "Who has an interest in the property",
              options: DEBTOR_LIABLE,
            },
          ],
        },
      ],
    },
    {
      id: "part3Household",
      title: "Part 3 — Personal and Household Items",
      description: "Estimate current value of items you own.",
      items: [
        { id: "householdGoods", type: "currency", label: "Household goods and furnishings" },
        { id: "householdGoodsDesc", type: "textarea", label: "Description" },
        { id: "electronics", type: "currency", label: "Electronics" },
        { id: "electronicsDesc", type: "textarea", label: "Description" },
        { id: "collectibles", type: "currency", label: "Collectibles of value" },
        { id: "collectiblesDesc", type: "textarea", label: "Description" },
        { id: "sportsEquipment", type: "currency", label: "Equipment for sports/hobbies" },
        { id: "sportsEquipmentDesc", type: "textarea", label: "Description" },
        { id: "firearms", type: "currency", label: "Firearms" },
        { id: "firearmsDesc", type: "textarea", label: "Description" },
        { id: "clothes", type: "currency", label: "Clothes" },
        { id: "jewelry", type: "currency", label: "Jewelry" },
        { id: "jewelryDesc", type: "textarea", label: "Description" },
        { id: "animals", type: "currency", label: "Animals (pets, livestock)" },
        { id: "animalsDesc", type: "textarea", label: "Description" },
        { id: "otherPersonal", type: "currency", label: "Any other personal/household items" },
        { id: "otherPersonalDesc", type: "textarea", label: "Description" },
      ],
    },
    {
      id: "part4Financial",
      title: "Part 4 — Financial Assets",
      items: [
        { id: "cashOnHand", type: "currency", label: "Cash on hand" },
        {
          kind: "repeating-group",
          id: "depositAccounts",
          label: "Deposit accounts (checking, savings, CD, etc.)",
          itemLabel: "Account",
          fields: [
            {
              id: "type",
              type: "select",
              label: "Type",
              options: [
                { value: "checking", label: "Checking" },
                { value: "savings", label: "Savings" },
                { value: "moneyMarket", label: "Money market" },
                { value: "cd", label: "Certificate of deposit" },
                { value: "brokerage", label: "Brokerage" },
                { value: "other", label: "Other" },
              ],
            },
            { id: "institution", type: "text", label: "Institution" },
            { id: "lastFour", type: "text", label: "Last 4 of account number" },
            { id: "balance", type: "currency", label: "Current balance" },
          ],
        },
        {
          kind: "repeating-group",
          id: "bondsAndStocks",
          label: "Bonds, mutual funds, publicly traded stocks",
          itemLabel: "Holding",
          fields: [
            { id: "issuer", type: "text", label: "Issuer or fund" },
            { id: "shares", type: "number", label: "Shares / units" },
            { id: "value", type: "currency", label: "Current value" },
          ],
        },
        {
          kind: "repeating-group",
          id: "retirement",
          label: "Retirement and pension accounts (401(k), IRA, etc.)",
          itemLabel: "Account",
          fields: [
            { id: "type", type: "text", label: "Account type" },
            { id: "institution", type: "text", label: "Institution" },
            { id: "value", type: "currency", label: "Current value" },
          ],
        },
        {
          kind: "repeating-group",
          id: "securityDeposits",
          label: "Security deposits and prepayments",
          itemLabel: "Deposit",
          fields: [
            { id: "heldBy", type: "text", label: "Held by" },
            { id: "purpose", type: "text", label: "Purpose" },
            { id: "amount", type: "currency", label: "Amount" },
          ],
        },
        {
          kind: "repeating-group",
          id: "otherFinancialAssets",
          label: "Annuities, trusts, education savings, patents, licenses, accounts receivable, support owed, other",
          itemLabel: "Item",
          fields: [
            { id: "description", type: "text", label: "Description" },
            { id: "value", type: "currency", label: "Current value" },
          ],
        },
      ],
    },
    {
      id: "part5Business",
      title: "Part 5 — Business-Related Property",
      description: "List only if you own or have an interest in business-related property.",
      items: [
        { id: "accountsReceivable", type: "currency", label: "Accounts receivable" },
        { id: "officeEquipment", type: "currency", label: "Office equipment, furnishings, supplies" },
        { id: "machinery", type: "currency", label: "Machinery, fixtures, equipment, supplies" },
        { id: "inventory", type: "currency", label: "Inventory" },
        { id: "intangibles", type: "currency", label: "Customer lists, mailing lists, other compilations" },
        { id: "otherBusiness", type: "currency", label: "Any other business-related property" },
        { id: "otherBusinessDesc", type: "textarea", label: "Description" },
      ],
    },
    {
      id: "part6Farm",
      title: "Part 6 — Farm- and Commercial-Fishing-Related Property",
      items: [
        { id: "farmAnimals", type: "currency", label: "Farm animals (livestock, poultry, fish)" },
        { id: "crops", type: "currency", label: "Crops — either growing or harvested" },
        { id: "farmEquipment", type: "currency", label: "Farm and fishing equipment, implements, machinery, fixtures" },
        { id: "farmSupplies", type: "currency", label: "Farm and fishing supplies, chemicals, feed" },
        { id: "otherFarm", type: "currency", label: "Any other farm- or fishing-related property" },
        { id: "otherFarmDesc", type: "textarea", label: "Description" },
      ],
    },
    {
      id: "part7Other",
      title: "Part 7 — All Other Property You Have Not Already Listed",
      items: [
        {
          kind: "repeating-group",
          id: "otherProperty",
          label: "Other property",
          itemLabel: "Item",
          fields: [
            { id: "description", type: "text", label: "Description" },
            { id: "value", type: "currency", label: "Current value" },
          ],
        },
      ],
    },
  ],
};
